-- Seed Data: Job Types (100 job types from PROFESSIONS_ANALYSIS.md)
-- Created: 2026-05-08

-- ============================================
-- BUILDING & CONSTRUCTION JOBS
-- ============================================
INSERT INTO job_types (name, category) VALUES
('Air Conditioning Installation', 'building-construction'),
('Air Conditioning Repair', 'building-construction'),
('Appliance Installation', 'building-construction'),
('Appliance Repair', 'building-construction'),
('Asbestos Removal', 'building-construction'),
('Bathroom Renovation', 'building-construction'),
('Blind & Curtain Installation', 'building-construction'),
('Bricklaying', 'building-construction'),
('Building Design & Plans', 'building-construction'),
('Cabinet Making / Joinery', 'building-construction'),
('Carpentry (General)', 'building-construction'),
('Ceiling Repair', 'building-construction'),
('Chimney Cleaning & Repair', 'building-construction'),
('Cladding Installation', 'building-construction'),
('Concrete Driveway', 'building-construction'),
('Concrete Slab', 'building-construction'),
('Concreting (General)', 'building-construction'),
('Decking Construction', 'building-construction'),
('Demolition', 'building-construction'),
('Door Installation', 'building-construction'),
('Drafting / Building Plans', 'building-construction'),
('Drainage Work', 'building-construction'),
('Drywall / Plasterboard', 'building-construction'),
('Earthmoving / Excavation', 'building-construction'),
('Electrical Installation', 'building-construction'),
('Electrical Repair', 'building-construction'),
('Fencing Installation', 'building-construction'),
('Fencing Repair', 'building-construction'),
('Fire Protection Systems', 'building-construction'),
('Flooring Installation', 'building-construction'),
('Gas Fitting', 'building-construction'),
('Glazing / Window Repair', 'building-construction'),
('Granny Flat Construction', 'building-construction'),
('Guttering', 'building-construction'),
('Handyman Services', 'building-construction'),
('Heating Installation', 'building-construction'),
('Home Automation', 'building-construction'),
('Home Extension', 'building-construction'),
('Home Theatre Installation', 'building-construction'),
('House Painting (Exterior)', 'building-construction'),
('House Painting (Interior)', 'building-construction'),
('Insulation Installation', 'building-construction'),
('Kitchen Renovation', 'building-construction'),
('Landscaping (Construction)', 'building-construction'),
('Lift/Elevator Service', 'building-construction'),
('New Home Build', 'building-construction'),
('Painting (Commercial)', 'building-construction'),
('Paving', 'building-construction'),
('Plastering', 'building-construction'),
('Plumbing Installation', 'building-construction'),
('Plumbing Repair', 'building-construction'),
('Pool Construction', 'building-construction'),
('Rendering', 'building-construction'),
('Renovation (General)', 'building-construction'),
('Retaining Wall', 'building-construction'),
('Roofing Installation', 'building-construction'),
('Roofing Repair', 'building-construction'),
('Scaffolding', 'building-construction'),
('Security System Installation', 'building-construction'),
('Shop Fitting', 'building-construction'),
('Signage Installation', 'building-construction'),
('Stonework', 'building-construction'),
('Surveying', 'building-construction'),
('Tiling', 'building-construction'),
('Wall Removal / Opening', 'building-construction'),
('Waterproofing', 'building-construction'),
('Welding', 'building-construction'),
('Window Installation', 'building-construction'),
('Window & Door Repair', 'building-construction');

-- ============================================
-- PROPERTY MAINTENANCE & GARDEN JOBS
-- ============================================
INSERT INTO job_types (name, category) VALUES
('Carpet Cleaning', 'maintenance-garden'),
('Commercial Cleaning', 'maintenance-garden'),
('End of Lease Cleaning', 'maintenance-garden'),
('Furniture Assembly', 'maintenance-garden'),
('Garden Design', 'maintenance-garden'),
('Garden Maintenance', 'maintenance-garden'),
('Gardening (General)', 'maintenance-garden'),
('House Cleaning', 'maintenance-garden'),
('Lawn Mowing', 'maintenance-garden'),
('Landscaping (Softscaping)', 'maintenance-garden'),
('Pest Control', 'maintenance-garden'),
('Pest Inspection', 'maintenance-garden'),
('Pool Cleaning', 'maintenance-garden'),
('Pool Maintenance', 'maintenance-garden'),
('Property Maintenance', 'maintenance-garden'),
('Pruning / Tree Trimming', 'maintenance-garden'),
('Rubbish Removal', 'maintenance-garden'),
('Spring Cleaning', 'maintenance-garden'),
('Tree Removal', 'maintenance-garden'),
('Turf Laying', 'maintenance-garden'),
('Wall Hanging / TV Mounting', 'maintenance-garden'),
('Waste Removal', 'maintenance-garden'),
('Window Cleaning', 'maintenance-garden');

-- ============================================
-- TRANSPORT & DELIVERY JOBS
-- ============================================
INSERT INTO job_types (name, category) VALUES
('Courier / Parcel Delivery', 'transport-delivery'),
('Delivery (General)', 'transport-delivery'),
('Driving Services', 'transport-delivery'),
('Food Delivery', 'transport-delivery'),
('Furniture Removal', 'transport-delivery'),
('Grocery Delivery', 'transport-delivery'),
('House/Office Moving', 'transport-delivery'),
('Junk Removal', 'transport-delivery');
