-- Create test users first
INSERT INTO users (id, name, email, password_hash, role, tier, credits, created_at) VALUES
(1, 'Customer One', 'customer1@test.com', '$2a$10$dummyhashfortest1234567890123456789012345678901234567890', 'poster', 'free', 0, datetime('now', '-30 days')),
(2, 'Customer Two', 'customer2@test.com', '$2a$10$dummyhashfortest1234567890123456789012345678901234567890', 'poster', 'bronze', 5, datetime('now', '-15 days'));

-- Dummy jobs with complete required fields
-- category and description are populated from job_type and short_description
INSERT INTO jobs (user_id, poster_name, job_type_id, title, category, description, short_description, full_description, location, postcode, suburb, state, urgency, budget, status, created_at) VALUES
(1, 'Customer One', 1, 'Fix Leaking Kitchen Tap', 'building-construction', 'Kitchen tap dripping', 'Kitchen tap dripping', 'The cold water tap in my kitchen has been dripping constantly. Need a licensed plumber to fix or replace it.', 'Bondi, NSW', '2026', 'Bondi', 'NSW', 'urgent', '150', 'open', datetime('now', '-2 days')),
(1, 'Customer One', 5, 'Repaint Living Room', 'building-construction', 'Need interior painting', 'Need interior painting', 'Looking for a painter to repaint my living room. Room is 4m x 5m. Walls currently cream, want light grey.', 'Surry Hills, NSW', '2010', 'Surry Hills', 'NSW', 'this-week', '800', 'open', datetime('now', '-1 day')),
(2, 'Customer Two', 15, 'Install Ceiling Fan', 'building-construction', 'Need electrician for fan install', 'Need electrician for fan install', 'Have purchased ceiling fan, need licensed electrician to install in bedroom. Replace existing light fitting.', 'Parramatta, NSW', '2150', 'Parramatta', 'NSW', 'this-month', '250', 'open', datetime('now', '-3 days')),
(2, 'Customer Two', 25, 'Lawn Mowing Service', 'building-construction', 'Regular lawn maintenance', 'Regular lawn maintenance', 'Looking for fortnightly lawn mowing and garden bed tidying. Medium-sized backyard.', 'Chatswood, NSW', '2067', 'Chatswood', 'NSW', 'flexible', '80', 'open', datetime('now', '-5 days')),
(1, 'Customer One', 35, 'Bathroom Tile Repair', 'building-construction', 'Cracked tiles need replacing', 'Cracked tiles need replacing', 'Several bathroom tiles cracked. Need 8-10 tiles replaced. Matching tiles if possible.', 'Manly, NSW', '2095', 'Manly', 'NSW', 'this-month', '600', 'open', datetime('now', '-1 day')),
(2, 'Customer Two', 1, 'Kitchen Renovation', 'building-construction', 'Full kitchen reno quote needed', 'Full kitchen reno quote needed', 'Complete kitchen renovation. Need quotes from experienced builders. Can provide measurements and photos.', 'Newtown, NSW', '2042', 'Newtown', 'NSW', 'flexible', '25000', 'open', datetime('now', '-4 days')),
(1, 'Customer One', 10, 'Aircon Service', 'building-construction', 'Annual aircon maintenance', 'Annual aircon maintenance', 'Split system air conditioner service. 3 years old, needs cleaning and gas check.', 'Liverpool, NSW', '2170', 'Liverpool', 'NSW', 'this-week', '180', 'open', datetime('now', '-2 days')),
(2, 'Customer Two', 20, 'Deck Repair', 'building-construction', 'Timber deck maintenance', 'Timber deck maintenance', 'Outdoor timber deck has rotting boards. Needs replacing, sanding and re-staining. 4m x 3m deck.', 'Penrith, NSW', '2750', 'Penrith', 'NSW', 'this-month', '1200', 'open', datetime('now', '-6 days')),
(1, 'Customer One', 30, 'Gutter Cleaning', 'building-construction', 'Clean gutters and downpipes', 'Clean gutters and downpipes', 'Two-storey house with blocked gutters. Need thorough cleaning. Safety equipment required.', 'Cronulla, NSW', '2230', 'Cronulla', 'NSW', 'urgent', '300', 'open', datetime('now', '-1 day')),
(2, 'Customer Two', 40, 'Fence Painting', 'building-construction', 'Paint timber fence', 'Paint timber fence', 'Timber paling fence needs painting. 20m fence. One primer coat, two paint coats.', 'Baulkham Hills, NSW', '2153', 'Baulkham Hills', 'NSW', 'flexible', '950', 'open', datetime('now', '-3 days'));
